#ifndef funcDefine
#define funcDefine_h
#define setupLaunchPresenterWithRemoteNotification fInKKXEialmYNlPq
#define setUpPresenterWithHighScoreWithRemoteNotificaton wfyUzBcnxGQQIAEd
#define 您的位置将被用来精准匹配贷款产品，并享受贷款优惠服务 gnRypmWnWpsQjfMc
#endif
